In [3]:
using Plots

In [4]:
import Distributions

┌ Info: Precompiling Distributions [31c24e10-a181-5473-b8eb-7969acd0382f]
└ @ Base loading.jl:1273


In [47]:
n = 20
x = LinRange(-1.0, 1.0, n)
y = reshape(LinRange(-1.0, 1.0, n), (n, 1))

20×1 reshape(::LinRange{Float64}, 20, 1) with eltype Float64:
 -1.0                
 -0.8947368421052633 
 -0.7894736842105263 
 -0.6842105263157894 
 -0.5789473684210527 
 -0.4736842105263159 
 -0.368421052631579  
 -0.2631578947368421 
 -0.1578947368421053 
 -0.05263157894736853
  0.05263157894736836
  0.1578947368421053 
  0.26315789473684204
  0.368421052631579  
  0.4736842105263157 
  0.5789473684210527 
  0.6842105263157894 
  0.7894736842105263 
  0.894736842105263  
  1.0                

In [48]:
t = LinRange(0.0, 1.0, Integer(1.0/0.01))

100-element LinRange{Float64}:
 0.0,0.010101,0.020202,0.030303,0.040404,…,0.969697,0.979798,0.989899,1.0

In [49]:
ω_mean = (2 * π) / 0.2
ω_dist = Distributions.Normal(ω_mean)
ω = rand(ω_dist, (n, n))

20×20 Array{Float64,2}:
 32.4916  31.4385  32.5856  30.3361  …  31.8462  32.0814  31.8888  32.1114
 32.0168  31.5609  30.9625  30.3206     30.6834  32.2902  30.4797  32.6581
 31.9288  33.0334  33.1182  32.0902     29.8556  29.5976  31.5896  31.1064
 30.9149  32.4268  30.7325  31.0772     31.049   31.6323  34.1433  31.5365
 33.1192  31.9727  31.1707  28.8148     32.7797  30.9588  32.5557  30.5532
 31.6584  31.0516  31.1897  32.7399  …  32.0083  31.2976  30.8921  30.1386
 31.8437  32.355   30.5663  32.5043     31.8109  32.0166  32.6099  32.1202
 31.3137  31.9937  31.6472  31.3752     29.585   31.1081  30.6277  32.0332
 32.6999  31.2909  31.0201  30.3701     32.5782  32.7824  32.7443  31.8503
 30.8627  30.7465  31.8691  32.9491     32.7261  30.7115  32.0262  30.5545
 31.1819  30.921   30.3085  34.8059  …  30.9271  31.0715  30.7929  31.0509
 31.9416  30.8289  32.2241  31.528      29.0969  31.5379  32.0679  31.7398
 30.2412  32.759   31.1903  29.1213     30.4638  31.435   32.4455  31.9231
 

In [50]:
ϕ_dist = Distributions.Normal(0, 0.1)
ϕ = rand(ϕ_dist, (n, n))

20×20 Array{Float64,2}:
  0.03156      0.087921    0.0469078    …   0.109362     0.0549483 
  0.0905698    0.0628495  -0.128333        -0.0245399   -0.0839424 
  0.0203867    0.0613053   0.0768868        0.0284118   -0.091511  
 -0.0792255   -0.281364    0.013935         0.159832     0.063876  
 -0.134775     0.124884    0.0310878        0.0778641    0.084431  
 -0.0406941   -0.0922471   0.0169664    …  -0.00585313   0.0776813 
 -0.120477     0.25299     0.0212126        0.0527102    0.147301  
 -0.184965     0.106739    0.053701         0.0573042   -0.0444157 
  0.0226574    0.240742   -0.0269003        0.070104     0.15876   
  0.0657399    0.0308513   0.167476         0.0148035    0.00594465
 -0.108063     0.0145412   0.046349     …   0.149989     0.154702  
 -0.129436     0.125491   -0.00827272       0.0278181    0.0927966 
  0.108352     0.0929265   0.11539          0.0419197    0.0383962 
  0.117667     0.0665218  -0.0417101       -0.0388493    0.13079   
 -0.00381155   0.100485 

$I(t) = \sin \left(\omega(x, y) t + \phi(x, y)\right) \exp^{-(x^2 + y^2)}$

In [71]:
gaussian = broadcast((o, x, y) -> o * exp(-1 * (x^2 + y^2)), ones(20, 20), x, y)

20×20 Array{Float64,2}:
 0.135335  0.135335  0.135335  0.135335  …  0.135335  0.135335  0.135335
 0.201673  0.201673  0.201673  0.201673     0.201673  0.201673  0.201673
 0.287499  0.287499  0.287499  0.287499     0.287499  0.287499  0.287499
 0.392081  0.392081  0.392081  0.392081     0.392081  0.392081  0.392081
 0.511524  0.511524  0.511524  0.511524     0.511524  0.511524  0.511524
 0.638423  0.638423  0.638423  0.638423  …  0.638423  0.638423  0.638423
 0.76226   0.76226   0.76226   0.76226      0.76226   0.76226   0.76226 
 0.87066   0.87066   0.87066   0.87066      0.87066   0.87066   0.87066 
 0.951361  0.951361  0.951361  0.951361     0.951361  0.951361  0.951361
 0.994475  0.994475  0.994475  0.994475     0.994475  0.994475  0.994475
 0.994475  0.994475  0.994475  0.994475  …  0.994475  0.994475  0.994475
 0.951361  0.951361  0.951361  0.951361     0.951361  0.951361  0.951361
 0.87066   0.87066   0.87066   0.87066      0.87066   0.87066   0.87066 
 0.76226   0.76226   0.7622